# Generated by Django 4.2.3 on 2023-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmodifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='user',
        ),
        migrations.AddField(
            model_name='link',
            name='png_with_qr',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='link',
            name='shortened_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
